load("@rules_cuda//cuda:defs.bzl", "cuda_library", "cuda_binary")

cuda_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)

cuda_binary(
    name = "pass-params",
    srcs = ["pass-params.cc"],
)

cuda_binary(
    name = "query-device",
    srcs = ["query-device.cc"],
)

cuda_binary(
    name = "choose-device",
    srcs = ["choose-device.cc"],
)
