load("@rules_cuda//cuda:defs.bzl", "cuda_library", "cuda_binary")

cuda_binary(
    name = "add_loop_blocks",
    srcs = ["add_loop_blocks.cu"],
)

cuda_binary(
    name = "add_loop_long_blocks",
    srcs = ["add_loop_long_blocks.cu"],
)